#!/bin/bash
# Generate BuildInfo.swift with build metadata
#
# This script is run as an Xcode Build Phase before "Compile Sources"
# to embed git commit, branch, timestamp, and build type into the app.
#
# IMPORTANT: This script NEVER fails the build. All errors result in
# fallback "unknown" values. No `set -e` is used.
#
# Usage: ./scripts/generate-build-info.sh <output_path>
# Example: ./scripts/generate-build-info.sh "${SRCROOT}/Muesli/Utilities/BuildInfo.swift"

# Output file path (passed from Xcode build phase)
OUTPUT_FILE="${1:-Muesli/Utilities/BuildInfo.swift}"

# Ensure output directory exists
mkdir -p "$(dirname "$OUTPUT_FILE")" 2>/dev/null || true

# ============================================================================
# Helper: Escape string for Swift string literal
# Handles backslashes, double quotes, and other special characters
# ============================================================================
escape_swift_string() {
    local input="$1"
    # Escape backslashes first, then double quotes
    echo "$input" | sed 's/\\/\\\\/g' | sed 's/"/\\"/g'
}

# ============================================================================
# Gather Build Information (with fallbacks)
# ============================================================================

# Git commit (short SHA)
GIT_COMMIT=$(git rev-parse --short HEAD 2>/dev/null) || GIT_COMMIT="unknown"

# Git branch (with fallback for detached HEAD)
GIT_BRANCH=$(git branch --show-current 2>/dev/null) || GIT_BRANCH="unknown"
if [ -z "$GIT_BRANCH" ]; then
    GIT_BRANCH="detached"
fi
# Escape for Swift string literal
GIT_BRANCH=$(escape_swift_string "$GIT_BRANCH")

# Check if working directory has uncommitted changes
if git diff --quiet HEAD 2>/dev/null && git diff --cached --quiet HEAD 2>/dev/null; then
    IS_DIRTY="false"
else
    IS_DIRTY="true"
fi

# Build timestamp (UTC ISO 8601 format for consistency)
BUILD_TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Build type from Xcode configuration (defaults to DEV if not set)
# CONFIGURATION is set by Xcode during builds
if [ "$CONFIGURATION" = "Release" ]; then
    BUILD_TYPE="RELEASE"
else
    BUILD_TYPE="DEV"
fi

# CI/GitHub Actions detection
if [ -n "$GITHUB_ACTIONS" ]; then
    CI_BUILD="true"
    # Include GitHub run info if available
    if [ -n "$GITHUB_RUN_NUMBER" ]; then
        CI_RUN_INFO="GitHub Actions #${GITHUB_RUN_NUMBER}"
    else
        CI_RUN_INFO="GitHub Actions"
    fi
else
    CI_BUILD="false"
    CI_RUN_INFO=""
fi

# ============================================================================
# Generate BuildInfo.swift
# ============================================================================

cat > "$OUTPUT_FILE" << 'SWIFT_HEADER'
// BuildInfo.swift
// Auto-generated by scripts/generate-build-info.sh - DO NOT EDIT
//
// This file is regenerated on every build to capture the exact
// git state and build timestamp for debugging purposes.

import Foundation

/// Build metadata captured at compile time for debugging and version identification.
///
/// Use this to verify which exact build is running:
/// - `gitCommit`: The git SHA when this binary was compiled
/// - `buildTimestamp`: When the build occurred (UTC)
/// - `buildType`: DEV (Debug) or RELEASE
/// - `isDirty`: Whether there were uncommitted changes
enum BuildInfo {
SWIFT_HEADER

# Write the static properties with actual values
cat >> "$OUTPUT_FILE" << EOF
    /// Short git commit SHA (e.g., "abc1234")
    static let gitCommit = "$GIT_COMMIT"
    
    /// Git branch name (e.g., "main", "feature/foo", or "detached")
    static let gitBranch = "$GIT_BRANCH"
    
    /// Build timestamp in UTC (ISO 8601 format)
    static let buildTimestamp = "$BUILD_TIMESTAMP"
    
    /// Build configuration: "DEV" (Debug) or "RELEASE"
    static let buildType = "$BUILD_TYPE"
    
    /// True if there were uncommitted changes when built
    static let isDirty = $IS_DIRTY
    
    /// True if built on CI (GitHub Actions)
    static let isCIBuild = $CI_BUILD
    
    /// CI run info (e.g., "GitHub Actions #123") or empty string
    static let ciRunInfo = "$CI_RUN_INFO"
EOF

# Write the computed properties (no variable substitution needed)
cat >> "$OUTPUT_FILE" << 'SWIFT_FOOTER'
    
    /// Human-readable build identifier for display
    static var displayIdentifier: String {
        var parts = [gitCommit]
        if isDirty { parts.append("dirty") }
        return parts.joined(separator: "-")
    }
    
    /// Full build info string for clipboard/debugging
    static var fullDescription: String {
        var lines = [
            "Version: \(Bundle.main.infoDictionary?["CFBundleShortVersionString"] as? String ?? "unknown")",
            "Build Type: \(buildType)",
            "Commit: \(gitCommit)\(isDirty ? " (dirty)" : "")",
            "Branch: \(gitBranch)",
            "Built: \(buildTimestamp)"
        ]
        if isCIBuild {
            lines.append("CI: \(ciRunInfo)")
        }
        return lines.joined(separator: "\n")
    }
}
SWIFT_FOOTER

# Log what was generated (visible in Xcode build log)
echo "Generated BuildInfo.swift:"
echo "  Commit: $GIT_COMMIT$([ "$IS_DIRTY" = "true" ] && echo " (dirty)")"
echo "  Branch: $GIT_BRANCH"
echo "  Type: $BUILD_TYPE"
echo "  Time: $BUILD_TIMESTAMP"
if [ "$CI_BUILD" = "true" ]; then
    echo "  CI: $CI_RUN_INFO"
fi

# Always exit successfully - never fail the build
exit 0
