// BuildInfo.swift
// Auto-generated by scripts/generate-build-info.sh - DO NOT EDIT
//
// This file is regenerated on every build to capture the exact
// git state and build timestamp for debugging purposes.

import Foundation

/// Build metadata captured at compile time for debugging and version identification.
///
/// Use this to verify which exact build is running:
/// - `gitCommit`: The git SHA when this binary was compiled
/// - `buildTimestamp`: When the build occurred (UTC)
/// - `buildType`: DEV (Debug) or RELEASE
/// - `isDirty`: Whether there were uncommitted changes
enum BuildInfo {
    /// Short git commit SHA (e.g., "abc1234")
    static let gitCommit = "dd35c49"
    
    /// Git branch name (e.g., "main", "feature/foo", or "detached")
    static let gitBranch = "feature/audio_system_tap"
    
    /// Build timestamp in UTC (ISO 8601 format)
    static let buildTimestamp = "2026-01-31T17:08:14Z"
    
    /// Build configuration: "DEV" (Debug) or "RELEASE"
    static let buildType = "DEV"
    
    /// True if there were uncommitted changes when built
    static let isDirty = true
    
    /// True if built on CI (GitHub Actions)
    static let isCIBuild = false
    
    /// CI run info (e.g., "GitHub Actions #123") or empty string
    static let ciRunInfo = ""
    
    /// Human-readable build identifier for display
    static var displayIdentifier: String {
        var parts = [gitCommit]
        if isDirty { parts.append("dirty") }
        return parts.joined(separator: "-")
    }
    
    /// Full build info string for clipboard/debugging
    static var fullDescription: String {
        var lines = [
            "Version: \(Bundle.main.infoDictionary?["CFBundleShortVersionString"] as? String ?? "unknown")",
            "Build Type: \(buildType)",
            "Commit: \(gitCommit)\(isDirty ? " (dirty)" : "")",
            "Branch: \(gitBranch)",
            "Built: \(buildTimestamp)"
        ]
        if isCIBuild {
            lines.append("CI: \(ciRunInfo)")
        }
        return lines.joined(separator: "\n")
    }
}
